<h1>Task 1:</h1>
In this assignment, you shall write a function that will test if a 4×4 matrix is singular, i.e. to determine if an inverse exists, before calculating it.

You shall use the method of converting a matrix to echelon form, and testing if this fails by leaving zeros that can’t be removed on the leading diagonal.

In [1]:
import numpy as np

In [2]:
# Our function will go through the matrix replacing each row in order turning it into echelon form.
# If at any point it fails because it can't put a 1 in the leading diagonal,
# we will return the value True, otherwise, we will return False.
# There is no need to edit this function.
def isSingular(A) :
    B = np.array(A, dtype=np.float64) # Make B as a copy of A, since we're going to alter it's values.
    try:
        fixRowZero(B)
        fixRowOne(B)
        fixRowTwo(B)
        fixRowThree(B)
    except MatrixIsSingular:
        return True
    return False

# This next line defines our error flag. For when things go wrong if the matrix is singular.
# There is no need to edit this line.
class MatrixIsSingular(Exception): pass

In [3]:
# Complete the fuction isSingular. You will need to define the functions fixRowZero(B), fixRowOne(B), fixRowTwo(B), and fixRowThree(B).
def fixRowZero(B):
    if B[0,0] == 0:
        B[0] = B[0] + B[1]
    if B[0,0] == 0:
        B[0] = B[0] + B[2]
    if B[0,0] == 0:
        B[0] = B[0] + B[3]
    if B[0,0] == 0:
        raise MatrixIsSingular()
    B[0] = B[0] / B[0,0]
    return B

def fixRowOne(B):
    B[1] = B[1] - B[1,0] * B[0]
    if B[1,1] == 0:
        B[1] = B[1] + B[2]
        B[1] = B[1] - B[1,0] * B[0]
    if B[1,1] == 0:
        B[1] = B[1] + B[3]
        B[1] = B[1] - B[1,0] * B[0]
    if B[1,1] == 0:
        raise MatrixIsSingular()
    B[1] = B[1] / B[1,1]
    return B

def fixRowTwo(B):
    B[2] = B[2] - B[2,0] * B[0]
    B[2] = B[2] - B[2,1] * B[1]
    if B[2,2] == 0:
        B[2] = B[2] + B[3]
        B[2] = B[2] - B[2,0] * B[0]
        B[2] = B[2] - B[2,1] * B[1]
    if B[2,2] == 0:
        raise MatrixIsSingular()
    B[2] = B[2] / B[2,2]
    return B

def fixRowThree(B):
    B[3] = B[3] - B[3,0] * B[0]
    B[3] = B[3] - B[3,1] * B[1]
    B[3] = B[3] - B[3,2] * B[2]
    if B[3,3] == 0:
        raise MatrixIsSingular()
    B[3] = B[3] / B[3,3]
    return B

In [4]:
A = np.array([
        [2, 0, 0, 0],
        [0, 3, 0, 0],
        [0, 0, 4, 4],
        [0, 0, 5, 5]
    ], dtype=np.float64)
isSingular(A)

True

In [5]:
fixRowZero(A)

array([[1., 0., 0., 0.],
       [0., 3., 0., 0.],
       [0., 0., 4., 4.],
       [0., 0., 5., 5.]])

In [6]:
fixRowOne(A)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 4., 4.],
       [0., 0., 5., 5.]])

In [7]:
fixRowTwo(A)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 1.],
       [0., 0., 5., 5.]])

In [8]:
fixRowThree(A)

MatrixIsSingular: 

In [9]:
A = np.array([
        [0, 7, -5, 3],
        [2, 8, 0, 4],
        [3, 12, 0, 5],
        [1, 3, 1, 3]
    ], dtype=np.float64)
isSingular(A)

False

In [10]:
fixRowZero(A)

array([[ 1. ,  7.5, -2.5,  3.5],
       [ 2. ,  8. ,  0. ,  4. ],
       [ 3. , 12. ,  0. ,  5. ],
       [ 1. ,  3. ,  1. ,  3. ]])

In [11]:
fixRowOne(A)

array([[ 1.        ,  7.5       , -2.5       ,  3.5       ],
       [-0.        ,  1.        , -0.71428571,  0.42857143],
       [ 3.        , 12.        ,  0.        ,  5.        ],
       [ 1.        ,  3.        ,  1.        ,  3.        ]])

In [12]:
fixRowTwo(A)

array([[ 1.        ,  7.5       , -2.5       ,  3.5       ],
       [-0.        ,  1.        , -0.71428571,  0.42857143],
       [ 0.        ,  0.        ,  1.        ,  1.5       ],
       [ 1.        ,  3.        ,  1.        ,  3.        ]])

In [13]:
fixRowThree(A)

array([[ 1.        ,  7.5       , -2.5       ,  3.5       ],
       [-0.        ,  1.        , -0.71428571,  0.42857143],
       [ 0.        ,  0.        ,  1.        ,  1.5       ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])